from django.conf import settings
from django.db import models
import secrets


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class SoftDeleteModel(models.Model):
    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True


class Tenant(TimeStampedModel, SoftDeleteModel):
    SUBSCRIPTION_CHOICES = [
        ('FREE', 'Trial / Free'),
        ('STARTER', 'Starter'),
        ('BUSINESS', 'Business'),
        ('ENTERPRISE', 'Enterprise'),
    ]

    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    is_active = models.BooleanField(default=True)
    subscription_tier = models.CharField(max_length=20, choices=SUBSCRIPTION_CHOICES, default='FREE')
    feature_usage = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    @property
    def employee_limit(self):
        """Returns the maximum number of employees allowed for the current tier."""
        limits = {
            'FREE': 5,
            'STARTER': 25,
            'BUSINESS': 100,
            'ENTERPRISE': 999999,  # Unlimited
        }
        return limits.get(self.subscription_tier, 5)

    @property
    def current_employee_count(self):
        """Returns the number of active employees for this tenant."""
        from apps.employees.models import EmployeeProfile
        return EmployeeProfile.objects.filter(tenant=self, is_deleted=False).count()


class Announcement(TimeStampedModel):
    PRIORITY_CHOICES = [
        ('LOW', 'Low'),
        ('NORMAL', 'Normal'),
        ('HIGH', 'High'),
    ]

    tenant = models.ForeignKey('core.Tenant', on_delete=models.CASCADE, null=True, blank=True, related_name='announcements')
    title = models.CharField(max_length=255)
    content = models.TextField()
    date = models.DateField()
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='NORMAL')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='announcements',
    )

    class Meta:
        ordering = ['-date', '-created_at']

    def __str__(self):
        return self.title


class InviteCode(TimeStampedModel):
    """
    One-time invite code generated by the platform host.
    Required to register a new company on the platform.
    """
    code = models.CharField(max_length=32, unique=True, db_index=True)
    label = models.CharField(max_length=100, blank=True, help_text="Optional label e.g. 'Acme Corp invite'")
    is_used = models.BooleanField(default=False)
    used_by = models.OneToOneField(
        'core.Tenant',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='invite_code',
    )
    used_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_invite_codes',
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        status = "Used" if self.is_used else "Available"
        return f"{self.code} [{status}]"

    @classmethod
    def generate(cls, created_by=None, label=''):
        """Generate a new cryptographically secure invite code."""
        code = secrets.token_urlsafe(16)[:24]  # 24-char URL-safe string
        return cls.objects.create(code=code, label=label, created_by=created_by)


class AuditLog(TimeStampedModel):
    ACTION_CHOICES = [
        ('CREATE', 'Create'),
        ('UPDATE', 'Update'),
        ('DELETE', 'Delete'),
    ]

    tenant = models.ForeignKey('core.Tenant', on_delete=models.CASCADE, null=True, blank=True, related_name='audit_logs')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='audit_logs')
    action = models.CharField(max_length=10, choices=ACTION_CHOICES)
    resource = models.CharField(max_length=100, db_index=True)  # e.g., 'EmployeeProfile'
    resource_id = models.CharField(max_length=100, db_index=True)
    changes = models.JSONField(default=dict, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user} {self.action} {self.resource} ({self.resource_id})"


class ContactMessage(TimeStampedModel):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20, blank=True, null=True)
    company = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()
    is_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Message from {self.name} ({self.email})"
