# Generated by Django 4.2 on 2026-03-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_announcement_tenant"),
        ("leaves", "0002_alter_leaverequest_status_leavepolicywindow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicywindow",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_policy_windows",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_types",
                to="core.tenant",
            ),
        ),
    ]
