# Generated by Django 4.2 on 2026-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_invite_code'),
        ('leaves', '0003_leavebalance_tenant_leavepolicywindow_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('tenant', 'name')},
        ),
    ]
