# Generated by Django 4.2 on 2026-04-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tenant_subscription_tier_auditlog'),
        ('employees', '0004_employeeprofile_reports_to_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('tenant', 'title')},
        ),
    ]
