# Generated by Django 4.2 on 2026-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_announcement_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
    ]
