# Generated by Django 4.2 on 2026-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
