# Generated by Django 4.2 on 2026-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tenant_subscription_tier_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
