# Generated by Django 4.2 on 2026-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password_reset_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("HR_MANAGER", "HR Manager"),
                    ("EMPLOYEE", "Employee"),
                    ("APPLICANT", "Job Applicant"),
                ],
                db_index=True,
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Successful Login"),
                    ("FAILED", "Failed Login"),
                    ("MFA_PENDING", "MFA Verification Pending"),
                    ("LOCKED", "Account Locked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="authenticat_resourc_b40bc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="authenticat_action_4a725a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["email", "timestamp"], name="authenticat_email_52dbf5_idx"
            ),
        ),
    ]
