# Generated by Django 4.2 on 2026-03-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_announcement_tenant"),
        ("authentication", "0002_customuser_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.tenant",
            ),
        ),
    ]
