# Generated by Django 4.2 on 2026-04-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
