# Generated by Django 4.2 on 2026-02-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rate_percent", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "ordering": ["min_income"],
            },
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="month",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed"),
                    ("PERCENTAGE", "Percentage of base salary"),
                ],
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="component_type",
            field=models.CharField(
                choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("payroll_run", "employee")},
            },
        ),
    ]
