# Generated by Django 4.2 on 2026-03-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_announcement_tenant"),
        ("payroll", "0002_taxslab_alter_payrollrun_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrun",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_runs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_components",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_structures",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="taxslab",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_slabs",
                to="core.tenant",
            ),
        ),
    ]
