# Generated by Django 4.2 on 2026-03-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollrun_tenant_payslip_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='payroll.payslip')),
            ],
        ),
    ]
