# Generated by Django 4.2 on 2026-03-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslipcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='component_type',
            field=models.CharField(blank=True, choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarystructurecomponent',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarycomponent'),
        ),
    ]
