# Generated by Django 4.2 on 2026-04-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tenant_subscription_tier_auditlog'),
        ('payroll', '0005_salarystructurecomponent_component_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponent',
            unique_together={('tenant', 'name')},
        ),
    ]
