# Generated by Django 4.2 on 2026-02-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in_timestamp", models.DateTimeField(blank=True, null=True)),
                ("clock_out_timestamp", models.DateTimeField(blank=True, null=True)),
                ("clock_in_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("clock_out_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("status", models.CharField(default="PRESENT", max_length=20)),
            ],
        ),
    ]
