# Generated by Django 4.2 on 2026-02-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_logs",
                to="employees.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="attendance_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to="attendance.attendancelog",
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancelog",
            unique_together={("employee", "date")},
        ),
    ]
