# Generated by Django 4.2 on 2026-02-08 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="requested_clock_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="requested_clock_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_attendance_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendancecorrectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("HALF_DAY", "Half Day"),
                    ("LATE", "Late"),
                ],
                db_index=True,
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="attendancecorrectionrequest",
            index=models.Index(
                fields=["status", "id"], name="attendance__status_0ea30e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["employee", "date"], name="attendance__employe_83a268_idx"
            ),
        ),
    ]
