# Generated by Django 4.2 on 2026-03-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_announcement_tenant"),
        ("attendance", "0005_attendance_geo_ip_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_corrections",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_logs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_policies",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="attendancepolicy",
            name="absent_if_no_checkin_by",
            field=models.TimeField(help_text="No clock-in by this time = ABSENT"),
        ),
        migrations.AlterField(
            model_name="attendancepolicy",
            name="check_out_end",
            field=models.TimeField(help_text="Expected end of work day"),
        ),
        migrations.AlterField(
            model_name="attendancepolicy",
            name="check_out_start",
            field=models.TimeField(help_text="Earliest allowed clock-out"),
        ),
        migrations.AlterField(
            model_name="attendancepolicy",
            name="half_day_if_checkout_before",
            field=models.TimeField(help_text="Checkout before this = HALF_DAY"),
        ),
        migrations.AlterField(
            model_name="attendancepolicy",
            name="late_grace_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
