# Generated by Django 4.2 on 2026-02-09 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(blank=True, help_text="e.g., 'Senior Software Engineer'", max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('current_resume', models.FileField(blank=True, null=True, upload_to='applicant_resumes/')),
                ('resume_parsed_data', models.JSONField(blank=True, default=dict)),
                ('resume_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed AI analysis results'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_fit_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI-calculated fit score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_skill_match',
            field=models.JSONField(blank=True, default=list, help_text='Skills matched against job requirements'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_resume_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Application Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interview Scheduled'), ('HIRED', 'Hired'), ('REJECTED', 'Not Selected')], db_index=True, default='APPLIED', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_message',
            field=models.TextField(blank=True, help_text='Neutral message shown to applicant'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='minimum_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default='Remote', max_length=100),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'applied_at'], name='recruitment_status_30e338_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['user', 'status'], name='recruitment_user_id_cd2c46_idx'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
