# Generated by Django 4.2 on 2026-03-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_applicantprofile_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Google Gemini API Key for parsing resumes', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable real AI parsing. If disabled, system falls back to mock.')),
                ('prompt_template', models.TextField(blank=True, default='Extract the following information from the resume and return ONLY a valid JSON object with keys: name (string), email (string), phone (string), skills (list of strings), experience_years (integer), headline (string), education (list of objects with degree, school, year), experience (list of objects with title, company, duration, description), summary (string overview).', help_text='System instructions for the AI on how to parse the resume')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
