# Generated by Django 4.2 on 2026-03-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_announcement_tenant"),
        ("recruitment", "0003_aisettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_profiles",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="core.tenant",
            ),
        ),
    ]
