# Generated by Django 4.2 on 2026-03-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_applicantprofile_tenant_candidate_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Application Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interview Scheduled'), ('HIRED', 'Hired'), ('REJECTED', 'Not Selected')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='recruitment.candidate')),
            ],
            options={
                'verbose_name_plural': 'Candidate Status Histories',
                'ordering': ['created_at'],
            },
        ),
    ]
