# Generated by Django 4.2 on 2026-04-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_announcement_tenant'),
        ('recruitment', '0005_candidatestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='core.tenant'),
        ),
    ]
