# Generated by Django 4.2 on 2026-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_aisettings_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='resume_parse_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks the total number of resumes parsed by this tenant'),
        ),
    ]
