# Generated by Django 4.2 on 2026-04-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_aisettings_resume_parse_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='tenant',
        ),
    ]
