from decimal import Decimal

from django.http import HttpResponse
from rest_framework import viewsets
from rest_framework.decorators import action

from apps.core.permissions import IsAdminOrHRManager, IsSelfOrAdminOrHR, HasBusinessTier
from apps.core.tenancy import resolve_tenant
from apps.core.utils import increment_feature_usage
from .models import PayrollRun, Payslip, TaxSlab, SalaryComponent, SalaryStructure, PayslipComponent
from .serializers import (

    PayrollRunSerializer, PayslipSerializer, TaxSlabSerializer,
    SalaryComponentSerializer, SalaryStructureSerializer
)

from .pdf_generator import generate_payslip_pdf


from django.db import transaction

class PayrollRunViewSet(viewsets.ModelViewSet):
    queryset = PayrollRun.objects.all()
    serializer_class = PayrollRunSerializer
    permission_classes = [IsAdminOrHRManager, HasBusinessTier]
    feature_key = 'payroll_runs'

    def get_queryset(self):
        user = self.request.user
        tenant = resolve_tenant(self.request)
        if not user.is_superuser and not tenant:
            return PayrollRun.objects.none()
        return PayrollRun.objects.filter(tenant=tenant).order_by('-month')

    def perform_create(self, serializer):
        """Create the PayrollRun and trigger background payslip generation."""
        from .tasks import generate_payslips_task

        employee_ids = self.request.data.get('employee_ids', None)
        tenant = resolve_tenant(self.request)

        payroll_run = serializer.save(tenant=tenant, status='DRAFT')
        increment_feature_usage(self.request, self.feature_key)

        # Attempt to dispatch to Celery; fall back to background thread if broker is unavailable
        try:
            generate_payslips_task.delay(
                payroll_run_id=payroll_run.id,
                tenant_id=tenant.id if tenant else None,
                employee_ids=employee_ids
            )
        except Exception as e:
            import threading
            import logging
            logger = logging.getLogger(__name__)
            logger.warning(f"Celery unavailable ({e}), running payslip generation in background thread.")
            
            def run_sync():
                import time
                from django.db import connection
                
                # Small delay to ensure caller returns their response
                time.sleep(0.5)
                try:
                    from .tasks import generate_payslips_task as task
                    task(payroll_run_id=payroll_run.id,
                         tenant_id=tenant.id if tenant else None,
                         employee_ids=employee_ids)
                except Exception as sync_err:
                    logger.error(f"Background thread payslip generation failed: {sync_err}")
                    from .models import PayrollRun as PR
                    PR.objects.filter(id=payroll_run.id).update(status='FAILED')
                finally:
                    connection.close()

            transaction.on_commit(lambda: threading.Thread(target=run_sync, daemon=True).start())


class TaxSlabViewSet(viewsets.ModelViewSet):
    queryset = TaxSlab.objects.all()
    serializer_class = TaxSlabSerializer
    permission_classes = [IsAdminOrHRManager]

    def get_queryset(self):
        user = self.request.user
        tenant = resolve_tenant(self.request)
        if not user.is_superuser and not tenant:
            return TaxSlab.objects.none()
        return TaxSlab.objects.filter(tenant=tenant).order_by('min_income')

    def perform_create(self, serializer):
        serializer.save(tenant=resolve_tenant(self.request))


class PayslipViewSet(viewsets.ModelViewSet):
    """
    Payslips are auto-generated by PayrollRuns.
    - LIST / RETRIEVE: available to all authenticated users (filtered by role).
    - DELETE: admin/HR only — removes a single generated payslip.
    - CREATE / UPDATE: disabled — payslips are managed through PayrollRun creation.
    """
    queryset = Payslip.objects.select_related('employee', 'employee__user', 'payroll_run').all()
    serializer_class = PayslipSerializer
    # Disable create and update — payslips are only generated automatically
    http_method_names = ['get', 'delete', 'head', 'options']

    def get_queryset(self):
        user = self.request.user
        tenant = resolve_tenant(self.request)
        if not user.is_superuser and not tenant:
            return Payslip.objects.none()

        queryset = Payslip.objects.select_related(
            'employee', 'employee__user', 'payroll_run'
        ).filter(tenant=tenant)

        if user.role in {'ADMIN', 'HR_MANAGER'}:
            return queryset
        return queryset.filter(employee__user=user)

    def get_permissions(self):
        if self.action == 'destroy':
            return [IsAdminOrHRManager()]
        return [IsSelfOrAdminOrHR()]

    def perform_destroy(self, instance):
        """Delete the payslip. If it's the last one in the payroll run, delete the run too."""
        payroll_run = instance.payroll_run
        instance.delete()
        # If no more payslips belong to this run, clean up the orphaned run
        if not Payslip.objects.filter(payroll_run=payroll_run).exists():
            payroll_run.delete()

    @action(detail=True, methods=['get'])
    def download(self, request, pk=None):
        payslip = self.get_object()
        pdf_bytes = generate_payslip_pdf(payslip)

        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="payslip_{payslip.id}.pdf"'
        return response



class SalaryComponentViewSet(viewsets.ModelViewSet):
    queryset = SalaryComponent.objects.all()
    serializer_class = SalaryComponentSerializer
    permission_classes = [IsAdminOrHRManager]

    def get_queryset(self):
        tenant = resolve_tenant(self.request)
        return SalaryComponent.objects.filter(tenant=tenant)

    def perform_create(self, serializer):
        serializer.save(tenant=resolve_tenant(self.request))


class SalaryStructureViewSet(viewsets.ModelViewSet):
    queryset = SalaryStructure.objects.all()
    serializer_class = SalaryStructureSerializer
    permission_classes = [IsAdminOrHRManager]

    def get_queryset(self):
        tenant = resolve_tenant(self.request)
        queryset = SalaryStructure.objects.filter(tenant=tenant)
        # Support filtering by employee ID via query param: ?employee=<id>
        employee_id = self.request.query_params.get('employee')
        if employee_id:
            queryset = queryset.filter(employee__id=employee_id)
        return queryset

    def perform_create(self, serializer):
        serializer.save(tenant=resolve_tenant(self.request))

    def perform_update(self, serializer):
        # Ensure tenant is always set on updates too
        serializer.save(tenant=resolve_tenant(self.request))

